"""baseline

Revision ID: eeef0147d1ed
Revises: 
Create Date: 2026-08-06 23:06:10.647483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeef0147d1ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'model_3d_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('12.0'))
    op.alter_column('menu_items', 'model_3d_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('menu_items', 'external_id')
    op.alter_column('orders', 'subtotal_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('orders', 'external_order_id')
    op.drop_constraint(op.f('recipe_ingredients_menu_item_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(op.f('recipe_ingredients_stock_item_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'menu_items', ['menu_item_id'], ['id'])
    op.create_foreign_key(None, 'recipe_ingredients', 'stock_items', ['stock_item_id'], ['id'])
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reservations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('reservations_table_id_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_restaurant_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'restaurants', ['restaurant_id'], ['id'])
    op.alter_column('restaurants', 'model_3d_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'model_3d_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_restaurant_id_fkey'), 'reservations', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reservations_table_id_fkey'), 'reservations', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reservations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reservations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredients_stock_item_id_fkey'), 'recipe_ingredients', 'stock_items', ['stock_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('recipe_ingredients_menu_item_id_fkey'), 'recipe_ingredients', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('external_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('orders', 'subtotal_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.add_column('menu_items', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('menu_items', 'model_3d_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menu_items', 'model_3d_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('12.0'))
    # ### end Alembic commands ###
